name: 'southperry'

services:
  app:
    build:
      context: ../../
      dockerfile: Dockerfile
    container_name: southperry_app
    restart: unless-stopped
    ports:
      - "8484:8484"
    environment:
      MONGO_URI: mongodb://southperry:southperry@southperry_mongo:27017/southperry
      MARIADB_DB_NAME: southperry
      MARIADB_USER: southperry
      MARIADB_PASSWORD: southperry
      MARIADB_HOST: southperry_mariadb
      MARIADB_PORT: 3306
      REDIS_ADDR: southperry_redis:6379
    networks:
      - southperry

networks:
  southperry:
    external: true
