name: 'southperry-infra'

services:
  mongo:
    image: mongo:7.0
    container_name: southperry_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./initdb.d:/docker-entrypoint-initdb.d:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: southperry
    networks:
      - southperry

  redis:
    image: redis:7.2
    container_name: southperry_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - southperry

volumes:
  mongo_data:
  redis_data:

networks:
  southperry:
    name: southperry
    driver: bridge